### ISSUE TITLE
Build Android Studio Error

### ISSUE THREAD

**Issue by HuuNguyen312** [RWebRTC/WebRTC-Android-Learn#1]
```
Information:Gradle tasks [:app:assembleDebug]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lde/tavendo/autobahn/ByteBufferInputStream;
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
Information:BUILD FAILED
Information:Total time: 58.616 secs
Information:2 errors
Information:0 warnings
Information:See complete output in console
```

**Comment by RWebRTC** [comment]
@ngochuu90 How did  you build it? git clone and open RAppRTC(NOT WebRTC-Android-Learn) with Android Studio?
Error 1: Reference [Here](http://stackoverflow.com/questions/34352591/android-error-converting-byte-to-dex)，clean and rebuild.
Error 2: Reference [Here](http://stackoverflow.com/questions/32807587/com-android-build-transform-api-transformexception), Add

```
defaultConfig {
    multiDexEnabled true
}
```

into the app/build.gradle

**Comment by HuuNguyen312** [comment]
It work. But error when start capturing screen
<img src="https://cloud.githubusercontent.com/assets/9895294/18900543/6c744f96-856c-11e6-979b-faf45daa36f5.png" height="400" alt="Screenshot"/>

**Comment by RWebRTC** [comment]
@ngochuu90 it works. And this is not the error. like
<img src="https://cloud.githubusercontent.com/assets/21374839/19469455/f5f12140-954d-11e6-88b1-e2d196c5f5e5.png" height="400" alt="Screenshot"/>

**Comment by HuuNguyen312** [comment]
@RWebRTC Thanks for your answer.
But still error, Camera not work. I've enabled camera permission

**Comment by RWebRTC** [comment]
@ngochuu90 ~~https://github.com/RWebRTC/WebRTC-Android-Learn/blob/master/RAppRTC/app/src/main/java/org/appspot/apprtc/PeerConnectionClient.java#L623
remove `//`~~
In SCREEN CAMERA SETTING, can select Screen Capture or Camera Capture.

**Comment by HuuNguyen312** [comment]
Work perfect. Thank you!

**Comment by ngochuu90** [comment]
Hi,
When I build lastest version, errors appear:

```
10-18 10:59:04.362 9843-9843/? E/art: dlopen("/data/app/org.appspot.apprtc-2/lib/arm64/libjingle_peerconnection_so.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "_ZNSt6__ndk18ios_base5clearEj" referenced by "/data/app/org.appspot.apprtc-2/lib/arm64/libjingle_peerconnection_so.so"...
10-18 10:59:04.363 9843-9843/? W/org.webrtc.Logging: Failed to load jingle_peerconnection_so: 
                                                     java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt6__ndk18ios_base5clearEj" referenced by "/data/app/org.appspot.apprtc-2/lib/arm64/libjingle_peerconnection_so.so"...
                                                         at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                         at java.lang.System.loadLibrary(System.java:989)
                                                         at org.webrtc.Logging.<clinit>(Logging.java:28)
                                                         at org.webrtc.EglBase14.isEGL14Supported(EglBase14.java:40)
                                                         at org.webrtc.EglBase.create(EglBase.java:86)
                                                         at org.webrtc.EglBase.create(EglBase.java:93)
                                                         at org.appspot.apprtc.CallActivity.onCreate(CallActivity.java:165)
                                                         at android.app.Activity.performCreate(Activity.java:5975)
                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
                                                         at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                         at android.os.Looper.loop(Looper.java:194)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
10-18 10:59:04.365 9843-9843/? I/org.webrtc.Logging: EglBase14: SDK version: 21. isEGL14Supported: true
10-18 10:59:04.376 9843-9843/? D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-18 10:59:04.376 9843-9843/? D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-18 10:59:04.376 9843-9843/? D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-18 10:59:04.376 9843-9843/? D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-18 10:59:04.376 9843-9843/? D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-18 10:59:04.394 9843-9843/? D/AndroidRuntime: Shutting down VM
10-18 10:59:04.403 9843-9843/? E/AppRTCMobileActivity: Fatal error: No static method checkIsOnMainThread()V in class Lorg/webrtc/ThreadUtils; or its super classes (declaration of 'org.webrtc.ThreadUtils' appears in /data/app/org.appspot.apprtc-2/base.apk)
                                                       
                                                       java.lang.NoSuchMethodError: No static method checkIsOnMainThread()V in class Lorg/webrtc/ThreadUtils; or its super classes (declaration of 'org.webrtc.ThreadUtils' appears in /data/app/org.appspot.apprtc-2/base.apk)
                                                           at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:85)
                                                           at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:73)
                                                           at org.appspot.apprtc.CallActivity.onCreate(CallActivity.java:166)
                                                           at android.app.Activity.performCreate(Activity.java:5975)
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
                                                           at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                           at android.os.Handler.dispatchMessage(Handler.java:111)
                                                           at android.os.Looper.loop(Looper.java:194)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```
