### ISSUE TITLE
Failed to load jingle_peerconnection_so

### ISSUE THREAD

**Issue by HuuNguyen312** [RWebRTC/WebRTC-Android-Learn#2]
Hi,
When I build lastest version, errors appear:

```
10-18 10:59:04.362 9843-9843/? E/art: dlopen("/data/app/org.appspot.apprtc-2/lib/arm64/libjingle_peerconnection_so.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "_ZNSt6__ndk18ios_base5clearEj" referenced by "/data/app/org.appspot.apprtc-2/lib/arm64/libjingle_peerconnection_so.so"...
10-18 10:59:04.363 9843-9843/? W/org.webrtc.Logging: Failed to load jingle_peerconnection_so: 
                                                     java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt6__ndk18ios_base5clearEj" referenced by "/data/app/org.appspot.apprtc-2/lib/arm64/libjingle_peerconnection_so.so"...
                                                         at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                         at java.lang.System.loadLibrary(System.java:989)
                                                         at org.webrtc.Logging.<clinit>(Logging.java:28)
                                                         at org.webrtc.EglBase14.isEGL14Supported(EglBase14.java:40)
                                                         at org.webrtc.EglBase.create(EglBase.java:86)
                                                         at org.webrtc.EglBase.create(EglBase.java:93)
                                                         at org.appspot.apprtc.CallActivity.onCreate(CallActivity.java:165)
                                                         at android.app.Activity.performCreate(Activity.java:5975)
                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
                                                         at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                         at android.os.Handler.dispatchMessage(Handler.java:111)
                                                         at android.os.Looper.loop(Looper.java:194)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
10-18 10:59:04.365 9843-9843/? I/org.webrtc.Logging: EglBase14: SDK version: 21. isEGL14Supported: true
10-18 10:59:04.376 9843-9843/? D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-18 10:59:04.376 9843-9843/? D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-18 10:59:04.376 9843-9843/? D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-18 10:59:04.376 9843-9843/? D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-18 10:59:04.376 9843-9843/? D/IMGSRV: gralloc_module_getimplementationformat:2526: usage=0x1000 > fmt=0x1
10-18 10:59:04.394 9843-9843/? D/AndroidRuntime: Shutting down VM
10-18 10:59:04.403 9843-9843/? E/AppRTCMobileActivity: Fatal error: No static method checkIsOnMainThread()V in class Lorg/webrtc/ThreadUtils; or its super classes (declaration of 'org.webrtc.ThreadUtils' appears in /data/app/org.appspot.apprtc-2/base.apk)

                                                       java.lang.NoSuchMethodError: No static method checkIsOnMainThread()V in class Lorg/webrtc/ThreadUtils; or its super classes (declaration of 'org.webrtc.ThreadUtils' appears in /data/app/org.appspot.apprtc-2/base.apk)
                                                           at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:85)
                                                           at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:73)
                                                           at org.appspot.apprtc.CallActivity.onCreate(CallActivity.java:166)
                                                           at android.app.Activity.performCreate(Activity.java:5975)
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
                                                           at android.app.ActivityThread.access$800(ActivityThread.java:169)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                           at android.os.Handler.dispatchMessage(Handler.java:111)
                                                           at android.os.Looper.loop(Looper.java:194)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by RWebRTC** [comment]
@ngochuu90 
Yes, it is a bug caused by:
- libboringssl.cr.so
- libc++_shared.so
- libprotobuf_lite.cr.so

I put the "x86/*.so" into "arm64-v8a/". 
I have fix it and please try it again. It works or not? Please tell me. 
Thank you!

**Comment by HuuNguyen312** [comment]
@RWebRTC I try put the x86/*.so into arm64-v8a/, but it doesn't work

**Comment by RWebRTC** [comment]
@ngochuu90 I have fix it, git pull please.

**Comment by HuuNguyen312** [comment]
Work perfect. Thank you!

**Comment by RWebRTC** [comment]
@ngochuu90 Can you speak Chinese? I have no idea about it, but I think it is useful to do something. #3

**Comment by ngochuu90** [comment]
No, I can't. I'm from VietNam.  I don't speak English well, I hope you could sympathize with me. :)
I searched  "small voice in WebRTC android demo" on Google, but it seems there is no solution. :(
